name: socialv
description: A new Flutter project.
publish_to: "none"

version: 7.2.2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_rename: ^1.5.3

  # Common packages
  nb_utils: ^6.1.0
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.0
  lottie: ^2.7.0

  # Media
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  just_audio: ^0.9.36
  syncfusion_flutter_pdfviewer: ^24.1.45
  photo_view: ^0.14.0
  appinio_video_player: ^1.2.2
  giphy_get: ^3.5.4
  video_player: ^2.8.2
  youtube_player_flutter: ^8.1.2
  visibility_detector: ^0.4.0+2
  flutter_svg: ^2.0.9

  # APIs
  http: ^1.1.2
  intl: ^0.18.1
  html: ^0.15.4

  flutter_html: ^3.0.0-beta.1
  flutter_html_table: ^3.0.0-beta.2
  google_mobile_ads: ^4.0.0

  # State Management Technique
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2

  # Share
  share_plus: ^7.2.1
  flutter_custom_tabs: ^1.2.1

  # Firebase
  firebase_crashlytics: ^3.4.9
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_messaging: ^14.7.10
  firebase_remote_config: ^4.3.8
  cloud_firestore: ^4.14.0

  # AUTHENTICATION
  google_sign_in: ^6.2.1
  the_apple_sign_in: ^1.1.1

  # Remote Notification
  onesignal_flutter: ^5.0.4

  # Story
  story_time: ^1.0.6
  numberpicker: ^2.1.2

  # Others
  flutter_emoji: ^2.5.1
  flutter_mentions: ^2.0.1
  flutter_portal: ^0.4.0
  linear_timer: ^2.0.0
  country_picker: ^2.0.23
  any_link_preview: ^3.0.1
  string_contains: ^2.3.0
  carousel_slider: ^4.2.1

  #Payment
  flutter_stripe: ^10.0.0
  razorpay_flutter: ^1.3.6

  # Agora
  agora_rtc_engine: ^5.2.0
  permission_handler: ^11.1.0

  flutter_localizations:
    sdk: flutter
  # go_router: ^12.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  mobx_codegen: ^2.6.0+1
  flutter_launcher_icons: ^0.9.2
  #flutter pub run flutter_launcher_icons:main
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/flag/
    - assets/icons/
    - assets/lottie/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

package_rename_config:
  android:
    app_name: "Travello" # (String) The display name of the android app
    package_name: "kz.infoservice.socialv" # (String) The package name of the android app
  #    override_old_package: # (Optional) (String) Use this to delete the old folder structure of MainActivity or to use the existing code with the new package name
  #    lang: # (Optional) (String) The android development language {kotlin(default) or java}

  ios:
    app_name: "Travello" # (String) The display name of the ios app
    bundle_name: "nurway" # (String) The bundle name of the ios app
    package_name: "kz.infoservice.socialv" # (String) The product bundle identifier of the ios app
#dart run package_rename
